spring.application.name=EcommerceBackendSystem

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

project.image=images/


spring.app.jwtExpirationMS=${DATASOURCE_EXPIRATIONS}
spring.app.jwtSecret=${DATASOURCE_SECRET}
spring.app.jwtCookie=${DATASOURCE_COOKIE}


spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
