spring.application.name=EcommerceBackendSystem

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

project.image=images/


spring.app.jwtExpirationMS=${DATASOURCE_EXPIRATIONS}
spring.app.jwtSecret=${DATASOURCE_SECRET}
spring.app.jwtCookie=${DATASOURCE_COOKIE}


spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG



spring.app.adminUsername=${DATASOURCE_adminUsername}
spring.app.adminEmail=${DATASOURCE_adminEmail}
spring.app.adminPassword=${DATASOURCE_adminPassword}
spring.app.userUsername=${DATASOURCE_userUsername}
spring.app.userEmail=${DATASOURCE_userEmail}
spring.app.userPassword=${DATASOURCE_userPassword}
spring.app.sellerUsername=${DATASOURCE_sellerUsername}
spring.app.sellerEmail=${DATASOURCE_sellerEmail}
spring.app.sellerPassword=${DATASOURCE_sellerPassword}

