spring.application.name=EcommerceBackendSystem

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

project.image=images/


spring.app.jwtExpirationMS=86400000
spring.app.jwtSecret=mySecret233ibsiuvbwijhjwbefiusbduvihhfbnmnbbhjb
spring.app.jwtCookie=springBootEcom

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
